theme: minima
title: My life as a Fullstack Developer
author: Bas van der Sluis
email: bas_vd_sluis@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My life as a Fullstack Developer

# social links
github_username:  basvandersluis # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
